services:

  frontend:
    container_name: shop-frontend
    build:
      context: ./infrastructure/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    user: "1000:1000"
    working_dir: /app
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    networks:
      - auth
      - note
    command: sh -c "npm install && npm run dev"


  broker:
    image: rabbitmq:4.3.5-alpine
    container_name: shop-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - auth
      - note

  auth-back:
    container_name: shop-auth-back
    build:
      context: ./services/auth
      dockerfile: ../../infrastructure/auth/Dockerfile
    volumes:
      - ./services/auth:/app
    ports:
      - "8080"
    networks:
      - auth
    depends_on:
      - broker

  auth-db:
    container_name: shop-auth-db
    image: postgres:18.6-alpine
    volumes:
      - auth-db-data:/var/lib/postgresql/18/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default}
      POSTGRES_DB: shop_auth_db
    networks:
      - auth

  note-back:
    container_name: shop-note-back
    build:
      context: ./services/notification
      dockerfile: ../../infrastructure/notification/Dockerfile
    volumes:
      - ./services/notification:/app
    ports:
      - "8080"
    environment:
      - PORT=8080
      - DB_HOST=notification-db
      - DB_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-default}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-shop_note_db}
    networks:
      - note
    depends_on:
      - broker

  note-db:
    container_name: shop-note-db
    image: mongo:7.0
    volumes:
      - note-db-data:/data/db
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-default}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-shop_note_db}
    networks:
      - note

volumes:
  auth-db-data:
  note-db-data:

networks:
  auth:
  note:
