services:

  frontend:
    container_name: shop-frontend
    build:
      context: ./infrastructure/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    user: "1000:1000"
    working_dir: /app
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    networks:
      - frontend
    command: sh -c "npm install && npm run dev"


  broker:
    image: rabbitmq:4.3.5-alpine
    container_name: shop-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - broker

  auth-back:
    container_name: shop-auth-back
    build:
      context: ./services/auth
      dockerfile: ../../infrastructure/auth/Dockerfile
    volumes:
      - ./services/auth:/app
    ports:
      - "8080"
    networks:
      - auth
      - frontend
      - broker
    depends_on:
      - broker

  auth-db:
    container_name: shop-auth-db
    image: postgres:18.6-alpine
    volumes:
      - auth-db-data:/var/lib/postgresql/18/data
    environment:
      POSTGRES_USER: ${AUTH_PG_USER:-postgres}
      POSTGRES_PASSWORD: ${AUTH_PG_PASSWORD:-default}
      POSTGRES_DB: shop_auth_db
    networks:
      - auth

  note-back:
    container_name: shop-note-back
    build:
      context: ./services/notification
      dockerfile: ../../infrastructure/notification/Dockerfile
    volumes:
      - ./services/notification:/app
    ports:
      - "8080"
    environment:
      - PORT=8080
      - DB_HOST=notification-db
      - DB_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-default}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-shop_note_db}
    networks:
      - note
      - frontend
      - broker
    depends_on:
      - broker

  note-db:
    container_name: shop-note-db
    image: mongo:7.0
    volumes:
      - note-db-data:/data/db
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-default}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-shop_note_db}
    networks:
      - note

  catalog-back:
    container_name: shop-catalog-back
    build:
      context: ./infrastructure/catalog/php
      dockerfile: Dockerfile
      args:
        - ${WWWUSER:-1000}
        - ${WWWGROUP:-1000}
    user: "${WWWUSER:-1000}:${WWWGROUP:-1000}"
    volumes:
      - ./services/catalog:/var/www/html
    networks:
      - catalog
      - frontend
      - broker

  catalog-server:
    container_name: shop-catalog-server
    build:
      context: ./infrastructure/catalog/nginx
      dockerfile: Dockerfile
    ports:
      - "8080"
    volumes:
      - ./services/catalog:/var/www/html
    depends_on:
      - catalog-back
    networks:
      - catalog
      - frontend
      - broker

  catalog-db:
    container_name: shop-catalog-db
    image: postgres:18.6-alpine
    volumes:
      - catalog-db-data:/var/lib/postgresql/18/data
    environment:
      POSTGRES_USER: ${CATALOG_PG_USER:-postgres}
      POSTGRES_PASSWORD: ${CATALOG_PG_PASSWORD:-default}
      POSTGRES_DB: shop_catalog_db
    networks:
      - catalog

  catalog-cache:
    container_name: shop-catalog-cache
    image: redis:8.10
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --requirepass ${CATALOG_REDIS_PASSWORD}
    networks:
      - catalog    

  catalog-storage:
    container_name: shop-catalog-storage
    build:
      context: ./infrastructure/catalog/minio
      dockerfile: Dockerfile
    volumes:
      - catalog-storage-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${CATALOG_MINIO_USER:-default}
      MINIO_ROOT_PASSWORD: ${CATALOG_MINIO_PASSWORD:-default}
      MINIO_CONSOLE_ADDRESS: ":9001"
    networks:
      - catalog

  order-back:
    container_name: shop-order-back
    build:
      context: ./infrastructure/order/php
      dockerfile: Dockerfile
      args:
        - ${WWWUSER:-1000}
        - ${WWWGROUP:-1000}
    user: "${WWWUSER:-1000}:${WWWGROUP:-1000}"
    volumes:
      - ./services/order:/var/www/html
    networks:
      - order
      - frontend
      - broker

  order-server:
    container_name: shop-order-server
    build:
      context: ./infrastructure/order/nginx
      dockerfile: Dockerfile
    ports:
      - "8080"
    volumes:
      - ./services/order:/var/www/html
    depends_on:
      - order-back
    networks:
      - order
      - frontend
      - broker

  order-db:
    container_name: shop-order-db
    image: postgres:18.6-alpine
    volumes:
      - order-db-data:/var/lib/postgresql/18/data
    environment:
      POSTGRES_USER: ${ORDER_PG_USER:-postgres}
      POSTGRES_PASSWORD: ${ORDER_PG_PASSWORD:-default}
      POSTGRES_DB: shop_order_db
    networks:
      - order

  order-cache:
    container_name: shop-order-cache
    image: redis:8.10
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --requirepass ${ORDER_REDIS_PASSWORD}
    networks:
      - order

  order-payment:
    container_name: shop-order-payment
    image: stripe/stripe-cli:latest
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
    command: 'listen --forward-to http://order-server:8080/api/order/stripe/webhook --skip-update'
    depends_on:
      - order-server
    networks:
      - order

  search-back:
    container_name: shop-search-back
    build:
      context: ./services/search
      dockerfile: ../../infrastructure/search/Dockerfile
      args:
        - WWWUSER=${WWWUSER:-1000}
        - WWWGROUP=${WWWGROUP:-1000}
    user: "${WWWUSER:-1000}:${WWWGROUP:-1000}"
    volumes:
      - ./services/search:/app
    ports:
      - "8080"
    environment:
      - SEARCH_PORT=${SEARCH_PORT:-8080}
      - SEARCH_ES_HOST=${SEARCH_ES_HOST:-http://search-engine:9200}
      - SEARCH_BROKER_URL=${SEARCH_BROKER_URL:-amqp://guest:guest@broker:5672/}
    networks:
      - search
      - frontend
      - broker
    depends_on:
      - search-engine
      - broker

  search-engine:
    container_name: shop-search-engine
    image: elasticsearch:8.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - search-engine-data:/usr/share/elasticsearch/data
    networks:
      - search

volumes:
  auth-db-data:
  note-db-data:
  catalog-db-data:
  catalog-storage-data:
  order-db-data:
  search-engine-data:

networks:
  frontend:
  broker:
  auth:
  note:
  catalog:
  order:
  search:

