package usecase

import "errors"

var (
	ErrEmailAlreadyTaken            = errors.New("email already taken")
	ErrInvalidPassword              = errors.New("invalid password")
	ErrPasswordIsNotStrongEnough    = errors.New("password must contain upper and lowercase letters, numbers and symbols")
	ErrPasswordHashFail             = errors.New("password hash failed")
	ErrTokenGenerationFail          = errors.New("failed to generate security token")
	ErrVerificationTokenSaveFail    = errors.New("failed to save verification token")
	ErrVerificationEmailSendFail    = errors.New("failed to send verification email")
	ErrTokenPairGenerationFail      = errors.New("unable to generate access and refresh tokens")
	ErrTokenPairSaveFail            = errors.New("unable to save access and refresh tokens")
	ErrUserIdNotFound               = errors.New("user with such id not found")
	ErrUnauthorizedAction           = errors.New("you have no permission for this action")
	ErrInvalidUpdateEmailToken      = errors.New("invalid update token")
	ErrSameEmail                    = errors.New("new email must be different from current")
	ErrInvalidCredentials           = errors.New("invalid user or password")
	ErrSameNewPassword              = errors.New("new password must be different from current one")
	ErrInvalidRefreshToken          = errors.New("invalid or expired refresh token")
	ErrUserEmailIsNotVerified       = errors.New("user email is not verified yet")
	ErrWrongVerificationToken       = errors.New("wrong verification token")
	ErrUserActivationFail           = errors.New("user activation failed")
	ErrEmailAlreadyVerified         = errors.New("email already verified")
	ErrEmptyEmail                   = errors.New("email can not be empty")
	ErrUserEmailNotFound            = errors.New("user email not found")
	ErrInvalidPasswordRecoveryToken = errors.New("invalid password recovery token")
	ErrPasswordResetEmailSendFail   = errors.New("failed to send password recovery email")
)
